const { random } = require("./random.js")
const min = require("./min.js")

test("gets the min of arrays of values of mixed types", () => {
  expect(min([2, 3, 4])).toBe(2)
  expect(min([-10, -5, -20])).toBe(-20)
  expect(min(random([10, 10, 10, 10]))).toBeLessThanOrEqual(1)
  expect(min(random([10, 10, 10, 10]))).toBeGreaterThanOrEqual(0)
  expect(min([2, 3, "four"])).toBeNaN()
  expect(min([null, undefined, 3])).toBeNaN()
  expect(min([true, false])).toBeNaN()
  expect(min([-Infinity, Infinity, 0])).toBe(-Infinity)
})

test("returns NaN when attempting to get the min of non-arrays", () => {
  expect(min()).toBeNaN()
  expect(min("foo")).toBeNaN()
  expect(min(null)).toBeNaN()
  expect(min(undefined)).toBeNaN()
  expect(min(() => {})).toBeNaN()
  expect(min({})).toBeNaN()
  expect(min([])).toBeNaN()
  expect(min(true)).toBeNaN()
  expect(min(false)).toBeNaN()
})
